import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "@/components/navbar/navbar";
import { registerLicense } from "@syncfusion/ej2-base";
import styles from "@/styles/Home.module.css";
import { GoLocation } from "react-icons/go";
// Registering Syncfusion license key
registerLicense(
  "ORg4AjUWIQA/Gnt2VVhkQlFaclxJXGFWfVJpTGpQdk5xdV9DaVZUTWY/P1ZhSXxQdkRiXn5YdHNQR2FaVEI="
);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hostel Management | আমিন ছাত্রাবাস</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/109535601?v=4"
        />
      </Head>

      <main className={styles.main}>
        <Navbar />
      </main>
    </>
  );
}
