import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hostel Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/109535601?v=4"
        />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {/* content here  */}
          this is home
        </div>

        <div className={styles.center}></div>
      </main>
    </>
  );
}
